// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pY1jbP8lV4fELi7HqDlKz3v312pChz8',
    appId: '1:630209049770:android:5134ddee13037adac60cd3',
    messagingSenderId: '630209049770',
    projectId: 'travit-web-af075',
    storageBucket: 'travit-web-af075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bYQbBYuH_0eYyfq5OdT-uZG_ygKRL24',
    appId: '1:630209049770:ios:ec4ac29265016265c60cd3',
    messagingSenderId: '630209049770',
    projectId: 'travit-web-af075',
    storageBucket: 'travit-web-af075.appspot.com',
    iosBundleId: 'com.example.travitWeb',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmY0nP3F5rj46_EGwDinw2vsSTGug24BA',
    appId: '1:630209049770:web:7d07de409476fac4c60cd3',
    messagingSenderId: '630209049770',
    projectId: 'travit-web-af075',
    authDomain: 'travit-web-af075.firebaseapp.com',
    storageBucket: 'travit-web-af075.appspot.com',
    measurementId: 'G-VBLKPC310E',
  );

}